### ISSUE TITLE
Did u fixed the spam issue?

### ISSUE THREAD

**Issue by ghost** [Muqsit/Tebex#12]
I mean the issue which spams in the console the command executed when found due players, not sure if you know it. Sometimes appear sometimes doesnt thats why im asking and not testing.

**Comment by mesiiiiiii** [comment]
btw i mean the issue which spams in the console the command executed when found due players, not sure if you know it

**Comment by mesiiiiiii** [comment]
Sometimes appear sometimes doesnt thats why im asking and not testing

**Comment by Muqsit** [comment]
Change debug level to 1 in pocketmine.yml

**Comment by ghost** [comment]
Its in 1 and still spamming, so i suppose you didnt fixed it

**Comment by Muqsit** [comment]
@mesiiiiiii Send the exact error message that's being spammed
