### ISSUE TITLE
Tebex plugin causing crash due to XUID retrieval failure

### ISSUE THREAD

**Issue by GabBiswajit** [Muqsit/Tebex#24]
Hey there,

I hope you're doing well. I wanted to report an issue related to the Tebex plugin. It seems that the plugin is causing a crash on my PocketMine-MP server. The crash log indicates that the crash is caused by the Tebex plugin failing to retrieve the XUID (Xbox User ID) of a player named "GAB BISWAJIT".

Steps to Reproduce:

Install the Tebex plugin on a PocketMine-MP server.
Have a player named "GAB BISWAJIT" join the server.
Crash Details:

PocketMine-MP version: 5.11.0 [Protocol 649]
Tebex plugin version: 0.1.10
PHP version: 8.2.13
OS: Linux
Error: Cannot retrieve XUID of player: GAB BISWAJIT

Additional Information:
I've included all the relevant details from the crash log above. Please let me know if you need any further information or if there's anything I can do to assist in resolving this issue.

Thank you for your attention to this matter.

**Comment by Muqsit** [comment]
@GabBiswajit Thanks for the report, can you send the result from executing `/tbx refresh` (in console or in-game), particularly the 'Game Type' field that is displayed.

**Comment by GabBiswajit** [comment]
![Uploading IMG_20240307_143734.jpg…]()

**Comment by Muqsit** [comment]
The image is broken

**Comment by GabBiswajit** [comment]
![Uploading IMG_20240307_143734.jpg…]()

**Comment by GabBiswajit** [comment]
@Muqsit idk why the image send broken every time
![Uploading Screenshot_2024-03-07-14-37-12-19_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by GabBiswajit** [comment]
Command output | Refreshing command queue... Command output | Refreshed command queue Command output | Offline commands fetched: 0 Command output | Online players due: 0

Can you fix this issue fast ?

**Comment by Muqsit** [comment]
Hmm, could you also send the output of `/tbx info`?

**Comment by GabBiswajit** [comment]
![Uploading IMG_20240311_000626.jpg…]()

**Comment by GabBiswajit** [comment]
@Muqsit 
```php

Command output | Tebex Account Command output | ID: 1329722
Command output | Domain: https://frostnetwork.tebex.io Command output | Name: FrostNetwork
Command output | Currency: USD ($)
Command output | Online Mode: Enabled
Command output | Game Type: Minecraft (Bedrock)
Command output | Event Logging: Enabled
Command output |
Command output | Tebex Server
Command output | ID: 1706430
Command output | Name: FrostNetwork
Command output |
Command output | Tebex API
Command output | Latency: 215ms

**Comment by Muqsit** [comment]
@GabBiswajit It appears your webstore is configured to use Minecraft (Bedrock) i.e., online mode. Offline-mode servers must use Minecraft (Offline/Geyser) as the project type. You may manage your projects by visiting this link: https://creator.tebex.io/projects

![image](https://github.com/Muqsit/Tebex/assets/15074389/0d9d3354-f770-4315-821d-ebb24bc3f38a)

**Comment by GabBiswajit** [comment]
From where i changed this ?

**Comment by Muqsit** [comment]
I believe project types can't be reconfigured (at least not without contacting Tebex). If its feasible, you may create a new project with the Offline type.

**Comment by GabBiswajit** [comment]
My server is connected with waterdog pe so which plugin I need to use for it ?? Can you tell me that please

**Comment by Muqsit** [comment]
@GabBiswajit In v0.1.13, the plugin auto-switches to offline mode configuration when xbox-auth=off. Could you try it out and see if the crash still occurs? https://poggit.pmmp.io/r/234776/Tebex_dev-59.phar

**Comment by GabBiswajit** [comment]
Let's check

**Comment by GabBiswajit** [comment]
Hey @Muqsit I get a problem I do offline/geyser and I do /buycraft secret {code} than the plugin is connected but in website it's not updated it's still showing : ```
Install the Tebex plugin on your game server or configure webhooks to this store```

**Comment by GabBiswajit** [comment]
And when i go on install plugin option there is no tebex pocketmine plugin 😕

**Comment by Muqsit** [comment]
@GabBiswajit Could you try v0.1.14 and see if that works?

**Comment by GabBiswajit** [comment]
@Muqsit still same it's updated on tebex
