### ISSUE TITLE
Undefined offset: 98550

### ISSUE THREAD

**Issue by ghost** [Muqsit/Tebex#3]
A player by a package on my buycraft shop.

I do the command /tebex dropall ig (at this moment the buyer was offline).
After, when the buyers want to join the server, there are Internal serveur error :

"Undefined offset: 98550" in "plugins/Tebex-master/src/muqsit/handler/due/playersList/OnlineTebexDuePlayerList" at line 35.

**Comment by Muqsit** [comment]
I'll need more information on this, this doesn't seem right. Please provide the crashdump.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/61470324/102008608-27c7d980-3d32-11eb-89ea-8bcf16b3733b.png)
